# Generated by Django 5.0.3 on 2024-03-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_candidateapplications_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='compnayName',
            new_name='companyName',
        ),
    ]
